-- Update passwords with correct bcrypt hashes (generated by application)

-- Admin User (Admin@123)
UPDATE users 
SET password = '$2a$10$GUKG4SRysqNp3cKdpjG60.p0pgOCYy./C6sfCdxXWmo2qX8GYxXN.'
WHERE dsa_unique_code = 'ADMIN001' OR email = 'admin@bom.com';

-- DSA User (dsa123)
UPDATE users 
SET password = '$2a$10$YldDm/Q5jC7X8GPIwYuJsuMFX8Q932qieCVa78GJZIAS0vMh.Ohwy'
WHERE dsa_unique_code = 'DSA12K93431' OR email = 'dsa001@example.com';
